# docker-compose.yml

version: "3.7"

services:
  acumuladora:
    image: acumuladora:1.0.0
    ports:
      - "7511:7511"
    networks:
      - RMS001
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "4"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.acumuladora.rule=Host(`r001.acumuladora.datarms.com`)
        - traefik.http.services.acumuladora.loadBalancer.server.port=7511
        - traefik.http.routers.acumuladora.service=acumuladora
        - traefik.http.routers.acumuladora.entrypoints=websecure
        - traefik.http.routers.acumuladora.tls.certresolver=letsencryptresolver

networks:
  RMS001:
    external: true
    name: RMS001
